feature/generate order_items based on forecast
farm-service/backend pull request #16
Opened 2024-04-22 13:06 UTC by elijahmylcev

2024-04-22 18:36 UTC, Tardigrada777 requested changes

2024-04-22 18:36 UTC, Tardigrada777 commented on app/configuration/server.py
> +        app.on_event('startup')(repeat_every(seconds=60 * 60 * 12)(generate_orders))
According to the documentation https://github.com/dmontagu/fastapi-utils/blob/master/fastapi_utils/tasks.py#L26 `repet_every` function:

> This function returns a decorator that modifies a function so it is periodically re-executed after its first call.

This means the `generate_orders` event will be repeated every 12 hours (according to the presented configuration). It's probably not we are expecting here.

2024-04-22 18:36 UTC, Tardigrada777 commented on app/domain/calculate_orders.py
> +from sqlalchemy.ext.declarative import DeclarativeMeta
Business logic code from the `domain` level is not allowed to import anything from the `db` layer.

2024-04-22 18:36 UTC, Tardigrada777 commented on app/domain/calculate_orders.py
> +from app.configuration.settings import logger
Business logic code from the `domain` level is not allowed to import anything from the `application` layer. Logger - is an application layer entity.

2024-04-22 18:36 UTC, Tardigrada777 commented on app/domain/calculate_orders.py
> +            logger.error(f'Exception occurred: {e}')
You can handle this exception on the layer above (e.g. on the application layer, where we describe the event code).

2024-04-22 18:36 UTC, Tardigrada777 commented on app/domain/calculate_orders.py
> +            recipe_model: Type[DeclarativeMeta],
You can use generic types here in order to avoid direct import of `db` layer entities.

2024-04-22 21:54 UTC, elijahmylcev commented on app/configuration/server.py
> +        app.on_event('startup')(repeat_every(seconds=60 * 60 * 12)(generate_orders))
Fixed

2024-04-23 06:47 UTC, Tardigrada777 requested changes

2024-04-23 06:47 UTC, Tardigrada777 commented on app/configuration/server.py
> +        app.on_event('startup')(generate_orders)
Do we really need to run this event on `startup`? Or it's enough to schedule it as a cron event?

2024-04-23 06:47 UTC, Tardigrada777 commented on app/domain/calculate_orders.py
> +            recipe_model: Generic[T],
This called `injection`: when we inject an object in runtime to function or method in order to use object in runtime.

It's probably OK for this specific case (I would go with constructor-based injection though). But let's try at least define types for models.

It's not OK that domain logic uses word "model" from the `db` layer.

We should rather:

1. Define type for repository - object with access to DB
2. Make `process` method depend on the type, not actual implementation details
3. Inject instance of repository class (that may use models inside) on the layer above

2024-04-23 13:09 UTC, Tardigrada777 commented
/improve

2024-04-23 14:59 UTC, elijahmylcev commented
@Tardigrada777 I have corrected all comments. All that remains is to fix the test (@ChaPerx64). I'm waiting for your comments!

2024-04-23 18:07 UTC, Tardigrada777 approved these changes

2024-04-23 20:53 UTC, Slautin1703 commented on app/domain/repositories/calculate_orders_repository_interface.py
> +            consumer_id: any,
@elijahmylcev i would kindly reccomend to use specific type for this parameter

2024-04-23 20:55 UTC, merged

2024-04-23 20:55 UTC, Slautin1703 commented on app/internal/events/calculate_orders_repository.py
> +        return await ProductIngredientAssociation.get_items_by_product(product_id)
as i think its better to return consistent data. So if there is no items - just return empty array